# Generated by Django 5.2.8 on 2025-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='avatar',
            field=models.ImageField(upload_to='freelancers/'),
        ),
    ]
