# Generated by Django 5.2.8 on 2025-12-09 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0003_freelancer_profession_freelancer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ['-rating', '-completed_jobs']},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='reviews',
            new_name='review_count',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='title',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='availability',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='county_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='professions/'),
        ),
        migrations.AddIndex(
            model_name='freelancer',
            index=models.Index(fields=['profession', 'is_active'], name='mygigs_free_profess_84c0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancer',
            index=models.Index(fields=['county', 'is_active'], name='mygigs_free_county_3ab840_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancer',
            index=models.Index(fields=['rating'], name='mygigs_free_rating_4741f1_idx'),
        ),
    ]
