# Generated by Django 6.0 on 2025-12-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0008_mpesatransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='status',
        ),
    ]
