# Generated by Django 5.2.8 on 2025-12-19 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0009_remove_mpesatransaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='freelancer-documents/')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mygigs.freelancer')),
            ],
        ),
    ]
