# Generated by Django 5.2.8 on 2025-12-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0010_freelancerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerdocument',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='freelancerdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='freelancerdocument',
            name='document_type',
            field=models.CharField(choices=[('id', 'National ID'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freelancerdocument',
            name='file',
            field=models.FileField(upload_to='freelancer_documents/'),
        ),
    ]
