# Generated by Django 5.2.8 on 2025-12-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0011_remove_freelancerdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='avatar',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
