# Generated by Django 5.2.8 on 2026-01-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygigs', '0012_alter_freelancer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='clerk_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='image',
            field=models.ImageField(null=True, upload_to='professions/'),
        ),
    ]
