# Generated by Django 5.2.8 on 2025-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerkprofile',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
